### ISSUE TITLE
Pistons can't push blocks inside kingdoms.

### ISSUE THREAD

**Issue by Gnomejar** [Rumsfield/konquest#288]
The pistons work fine on their own, but when they try to push a block, they do nothing. I imagine this is to protect the structures within the kingdom from flying machines, but it stops every machine inside instead of only at the border.

1. Place down any type of piston inside a kingdom.
2. Place block on front.
3. Activate piston.
4. Block doesn't get pushed.

Versions:
 - Konquest plugin version: 1.6.0
 - Spigot server version (put NA if not used): NA
 - Paper server version (put NA if not used): 1.20 (17)

Config File:
[core.txt](https://github.com/user-attachments/files/17935377/core.txt)

**Comment by Rumsfield** [comment]
Thanks for reporting this, I'll look into it.

**Comment by Rumsfield** [comment]
This appears to be an intended feature. When a kingdom is protected by not having enough online players, then all pistons are stopped inside of the kingdom's town/capital land. This is to prevent players from other kingdoms using pistons. There's no easy way to tell which player activates a piston reliably, or who "owns" a flying machine made of pistons, so there's no easy way to block some pistons but not others based on a player's kingdom relationship.

The workaround for this is to adjust the core.yml settings for offline kingdom protection. You can disable offline protection, or set the minimum player to 1 so that a single player may use pistons in their kingdom land, while being at risk of outnumbered attacks.
```yaml
    # Prevent enemy players from breaking any blocks in a Kingdom with no players online (true/false)
    no_enemy_edit_offline: false
    
    # Number of online players required for a Kingdom to be protected from enemy attacks (integer >= 0)
    no_enemy_edit_offline_minimum: 1
    
```
